repos:
  # - repo: local
  #   hooks:
  #     - id: replace-tokens
  #       name: Replace Privacy Tokens
  #       entry: ./replace_tokens.sh
  #       language: script
  #       pass_filenames: true
  #       stages: [pre-commit]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks
