repos:
  - repo: local
    hooks:
      - id: replace-tokens
        name: Replace Privacy Tokens
        entry: ./replace_tokens.sh
        language: script
        pass_filenames: true
        stages: [pre-commit]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.23.1 # 使用最新版本
    hooks:
      - id: gitleaks
