[workspace]
authors = ["Zion Pu <pu.007@qq.com>"]
channels = ["conda-forge"]
name = "wots"
platforms = ["linux-64"]
version = "1.0.0"

[tasks]
# 运行 wots（显示帮助）
wots = "python -m _wots"

[dependencies]
python = ">=3.14.4,<3.15"
typer = ">=0.25.1,<0.26"
rich = ">=15.0.0,<16"
