[prompt]
about_user = "A high school student."
response_preference = "Fluent and Not cumbersome"

[env]

# use git version (git+https://github.com/gptme/gptme) to get metadata
MODEL = "gemini/gemini-2.5-flash"
