[prompt]
about_user = "I am a curious human programmer."
response_preference = "Don't explain basic concepts"

[env]

OPENAI_BASE_URL = "https://xiaohumini.site/v1"
MODEL = "local/claude-3-7-sonnet-thinking"

GPTME_PATCH_RECOVERY = true
