[prompt]

about_user = "I am a curious human programmer."
response_preference = "Don't explain basic concepts"

[env]


#### 1. ollama (Tiny models struggled to adhere to the system prompt as effectively.)
# OPENAI_BASE_URL = "http://localhost:11434/v1"
# MODEL = "local/qwen2.5-coder"

#### 2. 302.ai

OPENAI_BASE_URL = "https://api.302.ai/v1"
MODEL = "local/gpt-4o-mini"

# Please set the OPENAI_API_KEY in your ~/.zshenv file to ensure privacy.
# export OPENAI_API_KEY="sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

#### 3. siliconflow.cn

TOOL_FORMAT = "markdown"                                              # Select the tool formal. One of `markdown`, `xml`, `tool`
TOOL_ALLOWLIST = "append,browser,chats,ipython,patch,read,save,shell" #Commaseparatedlistofallowedtools
TOOL_MODULES = "gptme.tools"                                          # List of python comma separated python module path

# Return file content in error for non-matching patches
GPTME_PATCH_RECOVERY = true

[rag]
enabled = false
