maxTokens=5120
includeBody=true

# Github Copilot was automatically enabled when gh logined

[OPENROUTER]
envKey=OPENROUTER_API_KEY
model=google/gemma-4-31b-it:free

[DEEPSEEK]
envKey=DISABLE_DEEPSEEK

; [GEMINI]
; envKey=DISABLE_GEMINI
;
[GEMINI]
envKey=GEMINI_API_KEY
