maxTokens=5120
includeBody=true

; [OPENROUTER]
; envKey=OPENROUTER_API_KEY
; model=nvidia/nemotron-3-super-120b-a12b:free
;
; [GEMINI]
; envKey=GEMINI_API_KEY
;

# [OLLAMA]
# model=smtek/Qwen3.8-27B:Q2_K_XL-12gb
# numCtx=4096

[OPENROUTER]
envKey=DISABLE_OPENROUTER

[DEEPSEEK]
envKey=DISABLE_DEEPSEEK

[GEMINI]
envKey=DISABLE_GEMINI

[OPENCODE]
compatible=true
url=https://opencode.ai/zen/go
path=/v1
model="mimo-v2.5"
envKey=OPENCODE_API_KEY
