maxTokens=5120
includeBody=true

# Github Copilot was automatically enabled when gh logined

[OPENROUTER]
envKey=OPENROUTER_API_KEY
model=nvidia/nemotron-3-ultra-550b-a55b:free

[DEEPSEEK]
envKey=DISABLE_DEEPSEEK

[GEMINI]
envKey=DISABLE_GEMINI

# [GEMINI]
# envKey=GEMINI_API_KEY
