cacheDir: C:\Users\zion\scoop\apps\pnpm\current\cache
stateDir: C:\Users\zion\scoop\apps\pnpm\current\state
storeDir: C:\Users\zion\scoop\apps\pnpm\current\store
registry: https://registry.npmmirror.com
