' This file is automatically generated from Podman Desktop preferences.
set FSO = CreateObject("Scripting.FileSystemObject")
Set WshShell = CreateObject("WScript.Shell")
if FSO.FileExists("C:\Users\zion\AppData\local\Programs\podman-desktop\Podman Desktop.exe") then
  WshShell.CurrentDirectory = "C:\Users\zion\AppData\local\Programs\podman-desktop"
  WshShell.Run """" & "C:\Users\zion\AppData\local\Programs\podman-desktop\Podman Desktop.exe" & """ --minimized", 0, False
end if
Set WshShell = Nothing
